todo_file = "todo.md" # Can be absolute or relative path
file_indent = 4       # Number of spaces per indent in todo.md
display_indent = 2     # Number of spaces per indent to render in the app

[normal_keymap]
"Ctrl+d" = "Quit"
"Ctrl+c" = "Quit"
"q" = "Quit"
"x" = "Toggle"
"Space" = "Toggle"
#"k" = "SelectionUp"
#"j" = "SelectionDown"
#"K" = "SelectionPrev"
#"J" = "SelectionNext"
"k" = "SelectionPrev"
"j" = "SelectionNext"
"h" = "SelectionOut"
"l" = "SelectionIn"
"Enter" = "SelectionIn"
#"Ctrl+k" = "MoveUp"
#"Ctrl+j" = "MoveDown"
#"Ctrl+K" = "MovePrev"
#"Ctrl+J" = "MoveNext"
"Ctrl+k" = "MovePrev"
"Ctrl+j" = "MoveNext"
"Ctrl+h" = "MoveOut"
"<" = "MoveOut"
"Shift+Tab" = "MoveOut"
"Ctrl+l" = "MoveIn"
">" = "MoveIn"
"Tab" = "MoveIn"
"d" = "Delete"
"y" = "Copy"
"p" = "PasteBelow"
"P" = "PasteAbove"
"n" = "AddTop"
"O" = "AddAbove"
"o" = "AddBelow"
"s" = "AddSubtask"
"e" = "Edit"
"a" = "Edit"
"A" = "Edit"
"i" = "EditBeginning"
"I" = "EditBeginning"
"c" = "EditClear"
"C" = "EditClear"
"(" = "SetStartDate"
"[" = "SetStartDate"
")" = "SetDueDate"
"]" = "SetDueDate"
"u" = "Undo"
"U" = "Redo"
"Ctrl+r" = "Redo"

[text_keymap]
"Ctrl+d" = "Quit"
"Ctrl+c" = "EditDone"
"Enter" = "AddBelow"
"Esc" = "EditDone"
"Tab" = "MoveIn"
"Shift+Tab" = "MoveOut"
